// Generated by: spec-api-design skill
// Source spec: .sdd/specs/003-folder-segregation-and-onboarding.spec.md, Section 8
// Target language: TypeScript
// DO NOT EDIT MANUALLY -- regenerated on spec revision

// ---------------------------------------------------------------------------
// Existing types referenced but NOT redefined here:
//   SourceConfig, GitHubTreeEntry, Manifest, ToolClassification,
//   InstallResult, ToolType, CategoryType
// See: src/models/types.ts
//
// New data model types referenced but NOT redefined here:
//   FolderDetectionResult, FolderItem, CrossFolderConflict,
//   ConflictCandidate, MergedSourceList, IndexFetchResult,
//   IndexUrlSetting
// See: artifacts/003-folder-segregation-and-onboarding/data-schemas.ts
// ---------------------------------------------------------------------------

import type {
  SourceConfig,
  GitHubTreeEntry,
  Manifest,
  ToolClassification,
} from '../../src/models/types';

import type {
  FolderDetectionResult,
  FolderItem,
  CrossFolderConflict,
  ConflictCandidate,
  MergedSourceList,
} from './data-schemas';

// --- 8.1.1 detectFolders ---

/** Input: flat array of tree entries from GitHub Tree API */
export type DetectFoldersInput = GitHubTreeEntry[];

/** Output: array of detected folders (see Section 7.1) */
export type DetectFoldersOutput = FolderDetectionResult[];

// --- 8.1.2 groupByFolder ---

export interface GroupByFolderInput {
  entries: GitHubTreeEntry[];   // flat tree entries
  folders: Set<string>;         // discovered folder names from detectFolders
}

/** Output: map from folder name to entries belonging to that folder */
export type GroupByFolderOutput = Map<string, GitHubTreeEntry[]>;

// --- 8.2.1 formatFolderName ---

/** Input: raw directory name, max 255 chars */
export type FormatFolderNameInput = string;

/** Output: formatted display label */
export type FormatFolderNameOutput = string;

// --- 8.2.2 getFolderNodes ---

export interface GetFolderNodesInput {
  source: SourceConfig;                 // source repository configuration
  entries: GitHubTreeEntry[];           // flat tree entries for the source
  folders: FolderDetectionResult[];     // detected folders from detectFolders()
}

/** Output: array of folder tree node items, sorted alphabetically */
export type GetFolderNodesOutput = FolderItem[];

// --- 8.3.1 classifyItem (modified) ---

/** Input: file path with folder prefix already stripped by caller */
export type ClassifyItemInput = string;

/** Output: existing ToolClassification type */
export type ClassifyItemOutput = ToolClassification;

// --- 8.3.2 stripFolderPrefix ---

export interface StripFolderPrefixInput {
  itemPath: string;           // full source path (e.g., "frontend-team/.github/agents/x.md")
  folders: Set<string>;       // set of discovered folder names
}

/** Output: path with folder prefix removed, or original if first segment not in folders */
export type StripFolderPrefixOutput = string;

// --- 8.4.2 detectCrossFolderConflict ---

export interface DetectCrossFolderConflictInput {
  itemPath: string;               // full source path with folder prefix
  folders: Set<string>;           // discovered folders for this source
  manifest: Manifest;             // current workspace manifest
  source: SourceConfig;           // source repository
  allEntries: GitHubTreeEntry[];  // all tree entries for the source
}

/** Output: conflict object if conflict exists, undefined otherwise */
export type DetectCrossFolderConflictOutput = CrossFolderConflict | undefined;

// --- 8.4.3 resolveConflict ---

/** Input: the conflict to resolve via quick-pick */
export type ResolveConflictInput = CrossFolderConflict;

/** Output: user-selected candidate or undefined if cancelled */
export type ResolveConflictOutput = ConflictCandidate | undefined;

// --- 8.5.1 normalizeIndexUrls ---

export interface NormalizeIndexUrlsInput {
  raw: unknown;                 // raw setting value from vscode.workspace.getConfiguration
  defaultUrls: string[];        // default index URL array fallback
}

/** Output: normalized array of index URL strings */
export type NormalizeIndexUrlsOutput = string[];

// --- 8.5.2 loadMultipleIndexes ---

/** Input: array of index URL strings, 1..10 elements */
export type LoadMultipleIndexesInput = string[];

/** Output: merged source list with fetch results (see Section 7.9) */
export type LoadMultipleIndexesOutput = MergedSourceList;
