// Generated by: spec-architecture skill
// Source spec: .sdd/specs/003-folder-segregation-and-onboarding.spec.md, Section 9
// Target language: TypeScript
// DO NOT EDIT MANUALLY -- regenerated on spec revision

// ---------------------------------------------------------------------------
// Configuration schema for the Awesome Coding Assistants VS Code extension.
// Defines all settings contributed via package.json "contributes.configuration"
// that are relevant to the folder segregation and onboarding features.
//
// Existing settings (unchanged by this spec) are included for completeness.
// Settings modified or introduced by this spec are marked accordingly.
// ---------------------------------------------------------------------------

// --- Existing Settings (Unchanged) ---

export interface SourceConfigSetting {
  url: string;                          // Required. GitHub repository URL (e.g., https://github.com/owner/repo)
  name: string;                         // Required. Display name for this source
  branch?: string;                      // Default: "main". Branch to read from
  authTokenKey?: string;                // Optional. SecretStorage key for GitHub PAT (private repos)
}

export interface ExistingSettings {
  /** User-configured source repositories.
   *  Type: array of SourceConfigSetting.
   *  Default: []. */
  'awesome-coding-assistants.sources': SourceConfigSetting[];

  /** Cache expiration time in minutes.
   *  Type: integer. Default: 1440 (24 hours). Valid: 5-43200. */
  'awesome-coding-assistants.cacheExpirationMinutes': number;

  /** Show all tools regardless of workspace detection.
   *  Type: boolean. Default: false. */
  'awesome-coding-assistants.showAllTools': boolean;

  /** Automatically check for updates on extension activation.
   *  Type: boolean. Default: true. */
  'awesome-coding-assistants.autoCheckUpdates': boolean;

  /** Interval in minutes between automatic update checks.
   *  Type: integer. Default: 60. Valid: 5-1440. */
  'awesome-coding-assistants.autoCheckIntervalMinutes': number;

  /** Detect new and removed items in source repositories.
   *  Type: boolean. Default: true. */
  'awesome-coding-assistants.newContentDetection': boolean;
}

// --- Modified Setting (FR-021) ---

export interface IndexUrlSetting {
  /** URL(s) to master index JSON file(s) listing available source repositories.
   *
   *  MODIFIED by spec 003: changed from type "string" to type "array"
   *  with items of type "string" (FR-021).
   *
   *  Runtime coercion (FR-022): if the stored value is a plain string
   *  (from a pre-migration configuration), it is coerced to a
   *  single-element array at runtime by normalizeIndexUrls().
   *
   *  Type: string[]. Default: ["https://raw.githubusercontent.com/jlacube/awesome-coding-assistants/main/index.json"].
   *  Valid: 1-10 elements (NFR-008). Each element: well-formed HTTPS URL (NFR-006).
   *  Description: "URLs to master index JSON files listing available source repositories.
   *    Add multiple URLs to merge catalogs from different sources (e.g., private + community)." */
  'awesome-coding-assistants.indexUrl': string[];
}

// --- package.json Configuration Schema (JSON Schema representation) ---

export const INDEX_URL_SCHEMA = {
  'awesome-coding-assistants.indexUrl': {
    type: 'array' as const,
    items: { type: 'string' as const },
    default: [
      'https://raw.githubusercontent.com/jlacube/awesome-coding-assistants/main/index.json',
    ],
    description:
      'URLs to master index JSON files listing available source repositories. ' +
      'Add multiple URLs to merge catalogs from different sources (e.g., private + community). ' +
      'Existing single-string values are automatically migrated.',
  },
} as const;

// --- Walkthrough Contribution Schema ---
// Not a VS Code setting but a package.json contribution. Included here for
// completeness since it is part of the extension configuration surface.

export const WALKTHROUGH_CONTRIBUTION = {
  id: 'getStarted',
  title: 'Get Started with Awesome Coding Assistants',
  description:
    'Configure your source catalog and start browsing coding assistant configurations.',
  steps: [
    {
      id: 'configureSource',
      title: 'Configure Your Source',
      description:
        'Set up where to find coding assistant configurations. ' +
        'Click the button below to open the index URL setting.',
      media: { markdown: 'media/walkthrough/configure-source.md' },
      completionEvents: ['onSettingChanged:awesome-coding-assistants.indexUrl'],
    },
    {
      id: 'browseCatalog',
      title: 'Browse the Catalog',
      description:
        'Explore available agents, prompts, rules, and other configurations. ' +
        'Click the button below to open the catalog.',
      media: { markdown: 'media/walkthrough/browse-catalog.md' },
      completionEvents: ['onView:awesomeCodingAssistants.catalog'],
    },
  ],
} as const;

// --- Command Contribution (FR-032, FR-033) ---

export const WALKTHROUGH_COMMAND = {
  command: 'awesome-coding-assistants.openWalkthrough',
  title: 'Get Started',
  category: 'Awesome Coding Assistants',
} as const;

// --- Constants ---

export const DEFAULT_INDEX_URLS: readonly string[] = [
  'https://raw.githubusercontent.com/jlacube/awesome-coding-assistants/main/index.json',
] as const;

export const MAX_INDEX_URLS = 10;                    // NFR-008
export const WALKTHROUGH_ID = 'getStarted';          // Section 7.11
export const WALKTHROUGH_FULL_ID =
  'jlacube.awesome-coding-assistants#getStarted';    // VS Code-scoped ID
export const DEFAULT_FOLDER_SENTINEL = '__default__'; // Section 7.1
export const DEFAULT_FOLDER_DISPLAY_NAME = 'Default'; // FR-009
