// Generated by: spec-data-model skill
// Source spec: .sdd/specs/003-folder-segregation-and-onboarding.spec.md, Section 7
// Target language: TypeScript
// DO NOT EDIT MANUALLY -- regenerated on spec revision

// ---------------------------------------------------------------------------
// Existing types referenced but NOT redefined here:
//   SourceConfig, SourceEntry, MasterIndex, InstallationEntry, Manifest,
//   CacheEntry, GitHubTreeEntry, GitHubTreeResponse, CatalogFileItem,
//   SourceItem, CategoryItem, CategoryType, ToolType, Bundle, BundleItem,
//   BundleCategoryItem, BundleNodeItem, BundleFileItem, InstallResult,
//   installationId()
// See: src/models/types.ts
// ---------------------------------------------------------------------------

import type { SourceConfig, GitHubTreeEntry, CategoryType, ToolType } from '../../src/models/types';

// --- 7.1 FolderDetectionResult ---

export interface FolderDetectionResult {
  folderName: string;       // max 255, no slashes, first path segment only
  isDefault: boolean;       // true for virtual "Default" folder (FR-006)
  entries: GitHubTreeEntry[]; // subset of tree entries belonging to this folder
}

// --- 7.2 FolderItem (new CatalogItem union member) ---

export interface FolderItem {
  kind: 'folder';           // discriminant
  source: SourceConfig;     // source repository this folder belongs to
  folderName: string;       // raw directory name (e.g., "frontend-team"), max 255
  displayName: string;      // formatted label (e.g., "Frontend Team"), max 255
  isDefault: boolean;       // true for virtual "Default" folder
}

// --- 7.6 CatalogItem (modified union) ---

// Re-export for clarity; actual modification occurs in src/models/types.ts
// CatalogItem = SourceItem | CategoryItem | CatalogFileItem | FolderItem

// --- 7.8 IndexUrlSetting (runtime-computed) ---

export interface IndexUrlSetting {
  urls: string[];           // 1..10 elements, each well-formed HTTPS URL
}

// --- 7.9 MergedSourceList (runtime-computed) ---

export interface MergedSourceList {
  sources: SourceConfig[];          // deduplicated by sourceKey()
  fetchResults: IndexFetchResult[]; // one per URL in indexUrl array
}

// --- 7.10 IndexFetchResult ---

export interface IndexFetchResult {
  url: string;              // well-formed HTTPS URL
  success: boolean;
  sourceCount: number | null; // >= 0 when success; null when failure
  error: string | null;       // non-empty when failure; null when success
}

// --- 7.11 WalkthroughDefinition (declarative, package.json) ---

export interface WalkthroughDefinition {
  id: string;               // unique within extension, e.g., "getStarted"
  title: string;            // max 100, plain text
  description: string;      // max 500, plain text
  steps: WalkthroughStep[]; // exactly 2 elements (FR-029)
}

// --- 7.12 WalkthroughStep ---

export interface WalkthroughStep {
  id: string;                // unique within walkthrough
  title: string;             // max 100, plain text
  description: string;       // max 500, plain text or markdown
  media: WalkthroughStepMedia;
  completionEvents: string[]; // at least one event per step
}

// --- 7.13 WalkthroughStepMedia ---

export interface WalkthroughStepMedia {
  markdown: string;          // relative path to .md file bundled in VSIX
}

// --- 7.14 CrossFolderConflict (runtime-computed) ---

export interface CrossFolderConflict {
  targetPath: string;            // workspace-relative path after folder prefix stripping
  candidates: ConflictCandidate[]; // 2+ elements
}

// --- 7.15 ConflictCandidate ---

export interface ConflictCandidate {
  fullSourcePath: string;    // includes folder prefix
  folderName: string;        // raw folder name, max 255
  folderDisplayName: string; // formatted display label, max 255
  source: SourceConfig;      // source repository
}
