// Generated by: spec-api-design skill
// Source spec: .sdd/specs/003-folder-segregation-and-onboarding.spec.md, Section 8
// Target language: TypeScript
// DO NOT EDIT MANUALLY -- regenerated on spec revision

// ---------------------------------------------------------------------------
// Existing error classes NOT redefined here:
//   ExtensionError, SourceUnreachableError, AuthFailedError,
//   RateLimitedError, PreviewFetchFailedError, InstallFailedError,
//   InvalidPathError, ManifestCorruptError, CacheError
// See: src/models/errors.ts
// ---------------------------------------------------------------------------

// --- Error code constants ---

export const ErrorCodes = {
  // New error codes introduced by this specification
  INDEX_FETCH_FAILED: {
    code: 'INDEX_FETCH_FAILED',
    userMessage: 'Failed to fetch index from {url}.',
    logLevel: 'warn' as const,  // 'error' when all URLs fail
  },
  INDEX_SCHEMA_INVALID: {
    code: 'INDEX_SCHEMA_INVALID',
    userMessage: 'Index at {url} has an invalid format.',
    logLevel: 'warn' as const,
  },
  INVALID_INDEX_URL_TYPE: {
    code: 'INVALID_INDEX_URL_TYPE',
    userMessage: '',  // not shown to user -- internal coercion fallback
    logLevel: 'warn' as const,
  },
  CONFLICT_CANCELLED: {
    code: 'CONFLICT_CANCELLED',
    userMessage: '',  // not shown to user -- silent cancellation
    logLevel: 'info' as const,
  },
  WALKTHROUGH_NOT_FOUND: {
    code: 'WALKTHROUGH_NOT_FOUND',
    userMessage: 'Unable to open the Get Started walkthrough.',
    logLevel: 'error' as const,
  },

  // Existing error codes relevant to this specification (referenced, not redefined)
  // INSTALL_FAILED:      see src/models/errors.ts InstallFailedError
  // INVALID_PATH:        see src/models/errors.ts InvalidPathError
  // SOURCE_UNREACHABLE:  see src/models/errors.ts SourceUnreachableError
} as const;

export type ErrorCode = keyof typeof ErrorCodes;

// --- Error class to FR mapping ---

/**
 * Maps each error code to the Section 4 FRs that define its behavior.
 * Used for traceability validation.
 */
export const ErrorToFRMapping: Record<string, string[]> = {
  INDEX_FETCH_FAILED: ['FR-024'],
  INDEX_SCHEMA_INVALID: ['FR-024'],
  INVALID_INDEX_URL_TYPE: ['FR-022'],
  CONFLICT_CANCELLED: ['FR-014'],
  WALKTHROUGH_NOT_FOUND: ['FR-032'],
  INSTALL_FAILED: ['FR-010', 'FR-011'],
  INVALID_PATH: ['FR-010'],
};
