// Generated by: spec-api-design skill
// Source spec: .sdd/specs/003-folder-segregation-and-onboarding.spec.md, Section 8
// Target language: TypeScript
// DO NOT EDIT MANUALLY -- regenerated on spec revision

// ---------------------------------------------------------------------------
// Existing interfaces referenced but NOT redefined here:
//   GitHubClient, ManifestManager, Installer, SourceRegistry,
//   CatalogTreeProvider, NewContentDetector
// See: src/services/*.ts, src/providers/*.ts
//
// Types from companion artifacts:
//   FolderDetectionResult, FolderItem, CrossFolderConflict,
//   ConflictCandidate, MergedSourceList, IndexFetchResult
// See: artifacts/003-folder-segregation-and-onboarding/data-schemas.ts
// ---------------------------------------------------------------------------

import type {
  SourceConfig,
  GitHubTreeEntry,
  Manifest,
  ToolClassification,
} from '../../src/models/types';

import type {
  FolderDetectionResult,
  FolderItem,
  CrossFolderConflict,
  ConflictCandidate,
  MergedSourceList,
} from './data-schemas';

// --- 8.1 Folder Discovery Interface ---

/**
 * Interface for folder detection operations.
 * Implementations operate as pure functions over the GitHubTreeEntry array
 * without issuing additional API requests (FR-003).
 */
export interface IFolderDetector {
  /**
   * Scan a flat array of GitHub tree entries to identify first-level
   * directories that qualify as folders.
   * FR-001, FR-002, FR-003, FR-006, FR-007
   */
  detectFolders(entries: GitHubTreeEntry[]): FolderDetectionResult[];

  /**
   * Partition tree entries into groups keyed by folder name.
   * FR-001, FR-004, FR-006
   */
  groupByFolder(
    entries: GitHubTreeEntry[],
    folders: Set<string>,
  ): Map<string, GitHubTreeEntry[]>;
}

// --- 8.2 Folder Display Interface ---

/**
 * Interface for folder name formatting and tree node construction.
 */
export interface IFolderDisplay {
  /**
   * Auto-format a raw directory name into a human-readable display label.
   * FR-008, FR-009
   */
  formatFolderName(rawName: string): string;
}

/**
 * Extended catalog tree provider methods for folder support.
 * These methods are added to the existing CatalogTreeProvider class.
 */
export interface IFolderTreeProvider {
  /**
   * Build folder tree nodes for a source repository.
   * FR-004, FR-005, FR-006, FR-007, FR-008, FR-009, FR-016
   */
  getFolderNodes(
    source: SourceConfig,
    entries: GitHubTreeEntry[],
    folders: FolderDetectionResult[],
  ): FolderItem[];
}

// --- 8.3 Item Classification Interface ---

/**
 * Interface for path-based item classification.
 * The classifyItem function signature is unchanged; the behavioral
 * modification (removing templates/ prefix stripping) is documented
 * in Section 8.3.1.
 */
export interface IItemClassifier {
  /**
   * Classify a file path into tool type and category.
   * The path SHALL have its folder prefix already stripped by the caller.
   * FR-017, FR-018
   */
  classifyItem(path: string): ToolClassification;
}

/**
 * Interface for folder prefix stripping.
 */
export interface IPathUtils {
  /**
   * Strip the first path segment from an item path when it matches
   * a discovered folder name.
   * FR-010, FR-011, FR-018
   */
  stripFolderPrefix(itemPath: string, folders: Set<string>): string;
}

// --- 8.4 Installation Interface ---

/**
 * Interface for cross-folder conflict detection and resolution.
 */
export interface IConflictResolver {
  /**
   * Check whether an item being installed conflicts with existing
   * manifest entries or sibling folder items at the same post-strip
   * target path.
   * FR-014, FR-015
   */
  detectCrossFolderConflict(
    itemPath: string,
    folders: Set<string>,
    manifest: Manifest,
    source: SourceConfig,
    allEntries: GitHubTreeEntry[],
  ): CrossFolderConflict | undefined;

  /**
   * Display a VS Code quick-pick prompt for the user to choose among
   * cross-folder conflicting items.
   * Returns undefined if the user dismissed without selecting.
   * FR-014, FR-015
   */
  resolveConflict(
    conflict: CrossFolderConflict,
  ): Promise<ConflictCandidate | undefined>;
}

// --- 8.5 Index URL Management Interface ---

/**
 * Extended source registry methods for multi-index URL support.
 * These methods are added to the existing SourceRegistry class.
 */
export interface IMultiIndexSourceRegistry {
  /**
   * Coerce the raw indexUrl VS Code setting value to a validated string[].
   * FR-021, FR-022, FR-023
   */
  normalizeIndexUrls(raw: unknown, defaultUrls: string[]): string[];

  /**
   * Fetch multiple index JSON files in parallel, union-merge their
   * source lists, and deduplicate by url@branch composite key.
   * FR-024, FR-025, FR-026, FR-027
   */
  loadMultipleIndexes(urls: string[]): Promise<MergedSourceList>;
}

// --- 8.7 Walkthrough Command Interface ---

/**
 * Interface for the walkthrough re-access command handler.
 */
export interface IWalkthroughCommand {
  /**
   * Open the onboarding walkthrough in the VS Code editor area.
   * FR-032, FR-033
   */
  openWalkthrough(): Promise<void>;
}
