// Generated by: spec-data-model skill
// Source spec: .sdd/specs/003-folder-segregation-and-onboarding.spec.md, Section 7
// Target language: TypeScript
// DO NOT EDIT MANUALLY -- regenerated on spec revision

// ---------------------------------------------------------------------------
// State machine: IndexUrl Coercion (Section 7.8)
//
// The indexUrl setting undergoes runtime type coercion from an unknown raw
// value to a validated string[]. This is modeled as a deterministic
// transformation with four input states mapping to two output states.
// ---------------------------------------------------------------------------

/**
 * Input classification for the raw indexUrl setting value.
 */
export enum IndexUrlInputType {
  STRING = 'string',
  STRING_ARRAY = 'string_array',
  UNDEFINED = 'undefined',
  INVALID = 'invalid',
}

/**
 * Output classification after coercion.
 */
export enum IndexUrlOutputType {
  NORMALIZED_ARRAY = 'normalized_array',
  DEFAULT_ARRAY = 'default_array',
}

/**
 * Coercion transition table.
 *
 * | From (Input)    | To (Output)       | Guard                                  | Side Effects                     |
 * |-----------------|-------------------|----------------------------------------|----------------------------------|
 * | STRING          | NORMALIZED_ARRAY  | typeof raw === 'string'                | Wrap in single-element array     |
 * | STRING_ARRAY    | NORMALIZED_ARRAY  | Array.isArray && all elements string   | Use as-is                        |
 * | UNDEFINED       | DEFAULT_ARRAY     | raw === undefined                      | None                             |
 * | INVALID         | DEFAULT_ARRAY     | none of the above                      | Log warning with type info       |
 *
 * Invalid transitions: Any transition not listed above SHALL be rejected.
 * In practice, every possible input type maps to exactly one output --
 * the classification is exhaustive.
 */
export const INDEX_URL_COERCION_TRANSITIONS: Record<IndexUrlInputType, IndexUrlOutputType> = {
  [IndexUrlInputType.STRING]: IndexUrlOutputType.NORMALIZED_ARRAY,
  [IndexUrlInputType.STRING_ARRAY]: IndexUrlOutputType.NORMALIZED_ARRAY,
  [IndexUrlInputType.UNDEFINED]: IndexUrlOutputType.DEFAULT_ARRAY,
  [IndexUrlInputType.INVALID]: IndexUrlOutputType.DEFAULT_ARRAY,
};

/**
 * Classify a raw setting value into an IndexUrlInputType.
 */
export function classifyIndexUrlInput(raw: unknown): IndexUrlInputType {
  if (raw === undefined) {
    return IndexUrlInputType.UNDEFINED;
  }
  if (typeof raw === 'string') {
    return IndexUrlInputType.STRING;
  }
  if (Array.isArray(raw) && raw.every((v: unknown) => typeof v === 'string')) {
    return IndexUrlInputType.STRING_ARRAY;
  }
  return IndexUrlInputType.INVALID;
}

/**
 * Validate that a coercion transition is valid.
 * Returns the expected output type for the given input type.
 */
export function validateIndexUrlCoercion(inputType: IndexUrlInputType): IndexUrlOutputType {
  const outputType = INDEX_URL_COERCION_TRANSITIONS[inputType];
  if (outputType === undefined) {
    throw new Error(`INVALID_STATE_TRANSITION: no coercion defined for input type "${inputType}"`);
  }
  return outputType;
}
